### ISSUE TITLE
How much GPU memory is required for running the demo of Campus?

### ISSUE THREAD

**Issue by gaobaoding** [zju3dv/mvpose#32] opened 2019-11-12 14:08 UTC
Hi guys, 
My GPU is GTX970m and the available memory is ~2.95 GB.
Do you know how much GPU memory is necessary for running the demo of Campus like :
`python ./src/m_utils/demo.py -d Campus`

it seems that my GPU memory is not enough :(

**Comment by lan786** [comment] 2019-11-13 03:17
In my case my GPU memory is 6GB and I'm unable to run it. As author said in previous issue that GTX1080ti is enough. 
Duplicate of #31

**Comment by gaobaoding** [comment] 2019-11-13 10:10
Hi @lan786,
thanks for your information. Wow, that memory is more than I thought.

**Comment by gaobaoding** [comment] 2019-11-13 10:13
@lan786 
btw, can you run the demo command that I mentioned above with your GPU?

**Comment by lan786** [comment] 2019-11-14 01:33
@gaobaoding  Hi, I already test it but facing memory issue. I mentioned it in issue 31. [https://github.com/zju3dv/mvpose/issues/31](url)

**Closed** 2019-12-01 03:58 UTC
